/**
 * Robots.txt 템플릿 및 생성 유틸리티
 */

export interface RobotsTemplate {
  name: string;
  description: string;
  content: string;
}

/**
 * 기본 Robots.txt 템플릿
 */
export const robotsTemplates: RobotsTemplate[] = [
  {
    name: '모든 크롤러 허용 (권장)',
    description: '모든 검색 엔진 봇이 사이트 전체를 크롤링할 수 있도록 허용합니다.',
    content: `# Robots.txt for ZIVO Medical Tourism Platform
# Allow all crawlers to access all content

User-agent: *
Allow: /

# Sitemap location
Sitemap: https://zivo.travel/sitemap.xml

# Crawl delay (optional, in seconds)
# Crawl-delay: 1
`,
  },
  {
    name: '특정 디렉토리 차단',
    description: '관리자 페이지, API 엔드포인트 등 민감한 경로를 차단합니다.',
    content: `# Robots.txt for ZIVO Medical Tourism Platform
# Block specific directories

User-agent: *
Allow: /

# Block admin and API paths
Disallow: /admin/
Disallow: /api/
Disallow: /private/

# Block authentication pages
Disallow: /auth/signin
Disallow: /auth/signup

# Block search result pages
Disallow: /*?search=*
Disallow: /*?filter=*

# Sitemap location
Sitemap: https://zivo.travel/sitemap.xml
`,
  },
  {
    name: '검색 엔진별 설정',
    description: 'Google, Bing, Naver 등 검색 엔진별로 다른 설정을 적용합니다.',
    content: `# Robots.txt for ZIVO Medical Tourism Platform
# Search engine specific rules

# Google
User-agent: Googlebot
Allow: /
Crawl-delay: 0

# Bing
User-agent: Bingbot
Allow: /
Crawl-delay: 1

# Naver
User-agent: Yeti
Allow: /
Crawl-delay: 1

# All other bots
User-agent: *
Allow: /

# Block sensitive paths for all bots
Disallow: /admin/
Disallow: /api/

# Sitemap location
Sitemap: https://zivo.travel/sitemap.xml
`,
  },
  {
    name: '엄격한 제한 (개발 중)',
    description: '사이트 전체를 크롤링하지 못하도록 차단합니다. 개발 중이거나 비공개 사이트에 사용합니다.',
    content: `# Robots.txt for ZIVO Medical Tourism Platform
# Disallow all crawlers (development mode)

User-agent: *
Disallow: /

# Sitemap location (optional)
# Sitemap: https://zivo.travel/sitemap.xml
`,
  },
];

/**
 * Sitemap URL을 포함한 기본 Robots.txt 생성
 */
export function generateDefaultRobots(sitemapUrl: string = 'https://zivo.travel/sitemap.xml'): string {
  return `# Robots.txt for ZIVO Medical Tourism Platform
# Generated by ZIVO SEO Admin

User-agent: *
Allow: /

# Sitemap location
Sitemap: ${sitemapUrl}

# Common paths to block (recommended)
# Disallow: /admin/
# Disallow: /api/
# Disallow: /private/

# Crawl delay (optional, in seconds)
# Crawl-delay: 1
`;
}

/**
 * Robots.txt 유효성 검증
 */
export interface RobotsValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

export function validateRobotsTxt(content: string): RobotsValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const lines = content.split('\n');

  let hasUserAgent = false;
  let hasSitemap = false;
  let currentUserAgent: string | null = null;

  lines.forEach((line, index) => {
    const trimmed = line.trim();
    const lineNumber = index + 1;

    // 빈 줄이나 주석은 건너뛰기
    if (!trimmed || trimmed.startsWith('#')) {
      return;
    }

    // User-agent 체크
    if (trimmed.toLowerCase().startsWith('user-agent:')) {
      hasUserAgent = true;
      const value = trimmed.substring('user-agent:'.length).trim();
      currentUserAgent = value;

      if (!value) {
        errors.push(`Line ${lineNumber}: User-agent 값이 비어있습니다.`);
      }
      return;
    }

    // Sitemap 체크
    if (trimmed.toLowerCase().startsWith('sitemap:')) {
      hasSitemap = true;
      const value = trimmed.substring('sitemap:'.length).trim();

      if (!value) {
        errors.push(`Line ${lineNumber}: Sitemap URL이 비어있습니다.`);
      } else if (!value.startsWith('http://') && !value.startsWith('https://')) {
        errors.push(`Line ${lineNumber}: Sitemap URL은 http:// 또는 https://로 시작해야 합니다.`);
      }
      return;
    }

    // Allow/Disallow 체크
    if (trimmed.toLowerCase().startsWith('allow:') || trimmed.toLowerCase().startsWith('disallow:')) {
      if (!currentUserAgent) {
        errors.push(`Line ${lineNumber}: User-agent 선언 없이 Allow/Disallow를 사용할 수 없습니다.`);
      }

      const directive = trimmed.toLowerCase().startsWith('allow:') ? 'Allow' : 'Disallow';
      const value = trimmed.substring(directive.length + 1).trim();

      if (directive === 'Disallow' && !value) {
        // Disallow: (빈 값)은 모든 것을 허용하는 것과 같음 - 경고만
        warnings.push(`Line ${lineNumber}: Disallow 값이 비어있습니다. 이는 모든 경로를 허용하는 것과 같습니다.`);
      }
      return;
    }

    // Crawl-delay 체크
    if (trimmed.toLowerCase().startsWith('crawl-delay:')) {
      const value = trimmed.substring('crawl-delay:'.length).trim();

      if (!value) {
        errors.push(`Line ${lineNumber}: Crawl-delay 값이 비어있습니다.`);
      } else if (isNaN(Number(value))) {
        errors.push(`Line ${lineNumber}: Crawl-delay 값은 숫자여야 합니다.`);
      }
      return;
    }

    // 알 수 없는 지시어
    if (trimmed.includes(':')) {
      const directive = trimmed.split(':')[0].trim();
      warnings.push(`Line ${lineNumber}: 알 수 없는 지시어 "${directive}"입니다.`);
    }
  });

  // 기본 검증
  if (!hasUserAgent) {
    errors.push('User-agent 지시어가 최소 1개 이상 필요합니다.');
  }

  if (!hasSitemap) {
    warnings.push('Sitemap URL을 추가하는 것을 권장합니다.');
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  };
}

/**
 * Robots.txt 미리보기 생성 (라인 번호 포함)
 */
export function formatRobotsPreview(content: string): string {
  const lines = content.split('\n');
  return lines
    .map((line, index) => {
      const lineNumber = String(index + 1).padStart(3, ' ');
      return `${lineNumber} │ ${line}`;
    })
    .join('\n');
}
